name = "wapa"
compatibility_date = "2025-09-10"

# Build de Astro
[build]
command = "npm run build"
pages_build_output_dir = "dist"

# Funciones de Pages
[functions]
directory = "./functions"


[vars]
META_PIXEL_ID = "1773971123502906"
META_ACCESS_TOKEN = "EAA73lvajPNEBPVMdYj1n5f3ZAtU2QxC0PEM4kIouDXVOXI8x9l3nwhWi6YPZC1DMjtfzVsbxqhmmXZCCZAaFZCiPdIeJCfHAxNPBCtGU8dBHBlTAs34tBmxswudqDZBrogZB84VDvxT7ZBixuA7Ob9aWRMmCJ3p92quy1px1o9uNyO4yYeaJXy7wpBTVGLgZCYUZCnzwZDZD"

